### ISSUE TITLE
demin recipe fails to find django

### ISSUE THREAD

**Issue by morganrallen** [timsavage/denim#1]
```
Traceback (most recent call last):
  File "/home/morgan/devel/ecologic/core/local/lib/python2.7/site-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/morgan/devel/ecologic/core/local/lib/python2.7/site-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/morgan/devel/ecologic/core/fabfile/__init__.py", line 15, in <module>
    from . import recipes
  File "/home/morgan/devel/ecologic/core/fabfile/recipes.py", line 42, in <module>
    from denim.recipes.django import ProvisionDjangoRecipe, DeployDjangoRecipe
ImportError: No module named django
```

**Comment by morganrallen** [comment]
Neither classes `ProvisionDjangoRecipe, DeployDjangoRecipe` exist in the repo.
